export const GET_CURRENCY_REQUESTED ='GET_CURRENCY_REQUESTED'
export const GET_CURRENCY_SUCCESS ='GET_CURRENCY_SUCCESS'
export const GET_CURRENCY_FAILED ='GET_CURRENCY_FAILED'

export const ADD_CURRENCY_REQUESTED ='ADD_CURRENCY_REQUESTED'
export const ADD_CURRENCY_SUCCESS ='ADD_CURRENCY_SUCCESS'
export const ADD_CURRENCY_FAILED ='ADD_CURRENCY_FAILED'

export const SELECT_CURRENCY_REQUESTED ='SELECT_CURRENCY_REQUESTED'
export const SELECT_CURRENCY_SUCCESS ='SELECT_CURRENCY_SUCCESS'

